//
//  FlightDetailInteractor.swift
//  TestFlightCenter
//
//  Created by Ahmad Waqas on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightDetailBusinessLogic
{
  func doSomething(request: FlightDetail.Something.Request)
}

protocol FlightDetailDataStore
{
    var selectedFlight: LogicalSingleFlight { get set }
}

class FlightDetailInteractor: FlightDetailBusinessLogic, FlightDetailDataStore
{
    var selectedFlight = LogicalSingleFlight()
    
  var presenter: FlightDetailPresentationLogic?
  var worker: FlightDetailWorker?
  var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FlightDetail.Something.Request)
  {
    worker = FlightDetailWorker()
    worker?.doSomeWork()
    
    let response = FlightDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
