//
//  FlightDetailViewController.swift
//  TestFlightCenter
//
//  Created by Ahmad Waqas on 20/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightDetailDisplayLogic: class
{
  func displaySomething(viewModel: FlightDetail.Something.ViewModel)
}

class FlightDetailViewController: UIViewController, FlightDetailDisplayLogic
{
  var interactor: FlightDetailBusinessLogic?
  var router: (NSObjectProtocol & FlightDetailRoutingLogic & FlightDetailDataPassing)?
    
    
    @IBOutlet weak var containerView: UIView!
    @IBOutlet weak var lblArrivalCityShortName: UILabel!
    @IBOutlet weak var lblArrivalCityLongName: UILabel!
    @IBOutlet weak var lblDestinationLongName: UILabel!
    @IBOutlet weak var lblDestinationCityShortName: UILabel!
    @IBOutlet weak var lblFlightNumber: UILabel!
    @IBOutlet weak var lblTerminal: UILabel!
    @IBOutlet weak var lblGate: UILabel!
    @IBOutlet weak var lblSeat: UILabel!
    @IBOutlet weak var imageQR: UIImageView!
    @IBOutlet weak var bazierView: UIView!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FlightDetailInteractor()
    let presenter = FlightDetailPresenter()
    let router = FlightDetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
    override func viewDidAppear(_ animated: Bool) {
        
    }
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
   print("\( router?.dataStore)")
    let request = FlightDetail.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: FlightDetail.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
