//
//  FlightsModels.swift
//  TestFlightCenter
//
//  Created by Ahmad Waqas on 14/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Flights
{
  // MARK: Use cases
  
  enum FlightModel
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        var flightHeadlineInfo: String = "Flight to Pakistan"
        init(flightHeadlineInfo: String) {
            self.flightHeadlineInfo = flightHeadlineInfo
        }
    }
  }
}
