//
//  FlightsWorker.swift
//  TestFlightCenter
//
//  Created by Ahmad Waqas on 14/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightStoreProtocol {
    func fetchFlightsList(completion: @escaping (FlightsAPIResult))
}
typealias FlightsAPIResult = (Result<[Flight], FlightStoreError>) -> Void

class FlightsWorker {
    var flightStoreProtocol: FlightStoreProtocol
    init(flightStoreProtocol: FlightStoreProtocol) {
        self.flightStoreProtocol = flightStoreProtocol
    }
    
    func getAllFlightList(completion: @escaping (FlightsAPIResult)) {
        flightStoreProtocol.fetchFlightsList { (result) in
            DispatchQueue.main.async {
                completion(result)
            }
        }
    }
}
