//
//  FlightsPresenter.swift
//  TestFlightCenter
//
//  Created by Ahmad Waqas on 14/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightsPresentationLogic
{
  func presentSomething(response: Flights.FlightModel.Response)
}

class FlightsPresenter: FlightsPresentationLogic
{
  weak var viewController: FlightsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Flights.FlightModel.Response)
  {
    let viewModel = Flights.FlightModel.ViewModel(flightHeadlineInfo: "Test string")
    viewController?.displaySomething(viewModel: viewModel)
  }
}
