//
//  FlightsInteractor.swift
//  TestFlightCenter
//
//  Created by Ahmad Waqas on 14/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightsBusinessLogic
{
  func doSomething(request: Flights.FlightModel.Request)
}

protocol FlightsDataStore
{
  var name: String { get set }
}

class FlightsInteractor: FlightsBusinessLogic, FlightsDataStore
{
  var presenter: FlightsPresentationLogic?
  var worker: FlightsWorker?
  var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Flights.FlightModel.Request)
  {
    worker = FlightsWorker()
    worker?.doSomeWork()
    
    let response = Flights.FlightModel.Response()
    presenter?.presentSomething(response: response)
  }
}
